const appname = "E-Commerce";
const appversion = "Version 2.4.7";
const credits = "@flutter_xo7";
const email = 'Email';
const emailHint = 'admin@gmail.com';
const password = 'Password';
const passwordHint = '**********';
const confirmPassword = "Confirm Password";
const name = 'Name';
const nameHint = "FLutter_xo7";
const forgetPassword = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termsAndConditions = "Terms and Conditions";
const alreadyHaveAnAccount = "Already have an account? ";
//Home strings for bottomnavigationbar
const home = "Home", categories = "Categories", cart = "Cart", account = "Account";